dist: xenial
sudo: required
before_install:
- sudo apt-get update
- sudo apt-get install tomcat7
- sudo apt-get install ant-optional
- mysql -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('root');"
- nvm ls
- nvm install 12
- nvm use node
- npm -v
- npx -v
- node -v
- env
- ls -l ./WebContent/WEB-INF/lib/seroUtils.jar
- sed -i '96s/.*/        return "'$SCADA_LTS_MILESTONE'";/' ./src/com/serotonin/mango/Common.java
- cd ./scadalts-ui
- npm run-script build-config -- $SCADA_LTS_MILESTONE $TRAVIS_BUILD_NUMBER $TRAVIS_BRANCH $TRAVIS_COMMIT $TRAVIS_PULL_REQUEST $TRAVIS_PULL_REQUEST_BRANCH
- cd ../
language: java
jdk:
- openjdk11
services:
- docker
- mysql
install:
# Skipping tests because it is better to start that as another task on Travis.
  - ant build-skip-test
  - ant test-junit
script:
  - ant create-war
branches:
  only:
  - "/^develop.*$/"
  - "/^master.*$/"
  - "/^release.*$/"
  - "/^feature/#1610.*$/"
notifications:
  email: false
env:
  matrix:
  - CATALINA_HOME=/usr/share/tomcat7
  global:
  - secure: AbO3W1BC2fYChnu4FoTzRRwQIsheniFkk+POQZTcii9opX+EuiA2c/0B9Ny6g8NQ1tSzYpk9Wss/hQUXU1SKsnKlnLf4/0GiUuSrqNEbKvibi+HIr9qDL2CXonF2EI7ouQwIM2Gsu3GaOGvidC3d6bYXKeRUyV6a/IehaKjEWIIiOUV6WldQQCF71DMdQnMGS2sOr4lt29EyDz7j4c+Kj35T0BnzPnKf/80gXULK4MrE1kY8JJNJS6dJmJ4W4qN1eHwV6cYOvChv8ZQspcgYBZvCAy6aENOalCzIfX+gbi+osu0MIDnfTf65w+UdEAqz9u54Bzx17WId80wXlXlsHtHAec/k7EpfHtQwND2Patzst4g6wWsq9w8pp9cQKcLK8UIxPj4wIn2DKzv7ynB/MkTx3SQ3qlYA2mlF3bMF6ihw89Fmxg+BSn8NFqZw3vr9fRsaRletZoIzZOzRynAbDw64VlipuVWbymXdROsmwcFttlvMZ9y0QmnCJozOHuA/hvjaG87Mkf5u42KrrlKoDiQYNlAIGKEmB8p7pnhBvmmoMSVkWn63kT6ChBnn5D+1ZkGY6/b5TxXonwjH2wmtGxlLUAuqhb/3694VvhX6Pb/NRKOxycYoIZzNduRU766hq/jP6UQIXKnIetoNEnvdt8i/3iLV10B+Koe4i1bwn3o=
  - secure: X4bCPtp1dJ205oAnaOM3fjTqGJo3kKoG36yUeReSOwVTq0fpcHsfITm5ovErsvUIInWmi1S9mvEDdDmZpIbAzG3yRr7TMs/o2GlbAe4orKoYUB3kKJj6Civ2cK3Hy4P3Ntt7GJEOMYpvx5uq0bgqtYTdkBky//7lDYeg0Wou1+d+WxLSGew45+DDcdoISMMk6ZYq2TswYP+oPx3Nra+PFNy1N3ymbhR+a+AehD7/787GMd6Ee8FKJFH2nsJuJYvUuGrBCq7jwv+bH97+pXukaroRoqj5sIPbGn2CqOsS1yyaOiXHb95737SnObCzYM69Rw3TFTSM85lUCJ4b56gXJzajoNpVs8SQtMqiv9L/C3znTlODWFbhGOIqR637H2Q+YNXacfXmIZilNjU9snXJuC2Fcotsyri7lBTWLo4IdMFkecJsFqIc5bAJqtgAu/RAb5HV8SkTYyMWTaXFezmrRwolbiMROOyzTqaJpgjRHjG8oji/6taD8ratDdPL+9FWpvR1koa1Xybh3245CL8vx8Kd5cQFRo09aGy1qUohY4umPggBTCv2O0SambKIArIrJTnrJYt+PfRz0N9nsf9/E+SZBcuMHgHhcL+bFl9oc5CqTt7rqhSFiSg7l4FU/0Fm7FdxaHMV27tgkGn+EbXcMK6mfve+sJGPKSEA9GRsynM=
after_script:
- wget https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.85/bin/apache-tomcat-7.0.85.tar.gz
- mkdir ./docker/app
- mv apache-tomcat-7.0.85.tar.gz ./docker/app
- ls -l ./docker/app/apache-tomcat-7.0.85.tar.gz
- cd ./docker/app
- echo `pwd`
- echo `ls -l`
- tar -zxvf apache-tomcat-7.0.85.tar.gz
- ls -l
- mv ./apache-tomcat-7.0.85/* ./
- rm -rf ./apache-tomcat-7.0.85
- cp ../../ScadaBR.war ./webapps
- ls -l ./webapps/ScadaBR.war
- cp ../../WebContent/WEB-INF/lib/mysql-connector-java-5.1.49.jar ./lib/
- ls -l ./lib/mysql-connector-java-5.1.49.jar
- cp -f ../config/context.xml ./conf/
- cat ./conf/context.xml
- cd ../
- pwd
- ls
- docker version
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- export TAGISSUE=`echo $TRAVIS_BRANCH | egrep -o '#[0-9]+' | head -n1 | sed -n 's/^#//p'`
- echo $TAGISSUE
- export TAG_DEV_OR_ISSUE=`if [ "$TRAVIS_BRANCH" == "develop" ]; then echo "siv_dev";
  else echo $TAGISSUE ; fi`
- echo $TAG_DEV_OR_ISSUE
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TAG_DEV_OR_ISSUE;  fi`
- export TAG=`if [ "$TAG" == "" ]; then echo "release"; else echo $TAG;  fi`
- echo $MY_IMG_NAME; echo $TAG; echo $TRAVIS_COMMIT
- docker build -t $MY_IMG_NAME:$TRAVIS_COMMIT .
- docker tag $MY_IMG_NAME:$TRAVIS_COMMIT $MY_IMG_NAME:$TAG
- docker push $MY_IMG_NAME:$TAG
